[package]
name = "sketch"
version = "0.1.0"
authors = ["Christian Duerr <contact@christianduerr.com>"]
edition = "2018"

[dependencies]
vte = { version = "0.8.0", default-features = false }
env_logger = "0.7.1"
libc = "0.2.77"
log = "0.4.11"
