[package]
name = "sketch"
version = "0.1.0"
authors = ["Christian Duerr <contact@christianduerr.com>"]
edition = "2021"

[dependencies]
bitflags = "2.6.0"
libc = "0.2.77"
mio = { version = "1.0.0", features = ["os-ext"] }
structopt = "0.3.21"
unicode-width = "0.1.8"
vte = "0.13.0"
